### ISSUE TITLE
Batch mint processing check for meta data validity

### ISSUE THREAD

**Issue by pbca26** [pbca26/komodo-tokens-wallet#31]
- [ ] check url validity
- [ ] check if url is reachable
- [ ] check id validity
- [ ] check royalty validity
- [ ] check arbitrary JSON validity
